/* ==========================================
 * TABLE: GCG_4648_JOBSUM
 * ========================================== */
CREATE TABLE "GCG_4648_JOBSUM"(
 "RUN_ID" INTEGER,
 "JOB" CHAR(6),
 "SUFFIX" CHAR(6),
 "DESCRIPTION" CHAR(30),
 "AMT_MATERIAL" DOUBLE,
 "NUM_HOURS" DOUBLE,
 "AMT_LABOR" DOUBLE,
 "AMT_PRICE_PER_UNIT" DOUBLE,
 "QTY_CUSTOMER" DOUBLE,
 "QTY_ORDER" DOUBLE,
 "QTY_RECEIVED" DOUBLE,
 "COST" DOUBLE,
 "PURCHASE_ORDER" CHAR(7),
 "PART" CHAR(20),
 "NAME_CUSTOMER" CHAR(30),
 "FLAG_RECV_CLOSE" CHAR(1),
 "NAME_N" CHAR(50),
 "ENGN_HOURS" DOUBLE,
 "PROD_HOURS" DOUBLE,
 "RECORD_NO" CHAR(4));


